"""initial migration

Revision ID: bb4e7b9ac262
Revises: b3e355568d47
Create Date: 2016-11-02 14:35:50.911268

"""

# revision identifiers, used by Alembic.
revision = 'bb4e7b9ac262'
down_revision = 'b3e355568d47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
